Master feat resource(#sam 337)
totem-it/sam-skeleton pull request #3
Opened 2024-10-07 19:31 UTC by rooosiu

2024-10-07 20:05 UTC, rudashi requested changes

2024-10-07 20:05 UTC, rudashi commented on tests/Resource/ApiResourceTest.php
> +it('can create Collection via collection() method', function (): void {
nazwa testu sugeruje test metody laravel. Test za to sprwadza czy metoda collection zwraca inną klasę niż domyślna

2024-10-07 20:05 UTC, rudashi commented on tests/Resource/ApiResourceTest.php
> +test('resources may have optional attributes', function (): void {
Resource nie ma atrybutów, tylko Model. Nazwa testu mówi o czymś innym niż jest testowane

2024-10-07 20:05 UTC, rudashi commented on tests/Resource/ApiResourceTest.php
> +        ->sequence(
klucze przetestuj w sequence.

2024-10-07 20:05 UTC, rudashi commented on tests/Resource/FixtureModel.php
> +class FixtureModel extends Model
Modele definiujemy poprzez constructor.

2024-10-08 07:53 UTC, rudashi commented on README.md
> +- `noContent()` - creates an ApiResource instance with `true` as the resource value, which allows the response to be returned with an HTTP 204 No Content code.
```
Creates an `ApiResource` instance with `true` as the resource value
 ```
używającego tej metody nie obchodzi to. Po co ta informacja?

```
 This status indicates that the operation was successful but does not return any content.
```
Informacja że to status 204 no content mówi sama za siebie. Po co ta informacja?

2024-10-08 07:59 UTC, rooosiu commented on tests/Resource/AdditionalResourceDataTest.php
> +    $this->resource = new ApiResource([fake()->word() => fake()->word()]);
faktycznie nie są więc usunąłem

2024-10-08 08:05 UTC, rooosiu commented on tests/Resource/ApiCollectionTest.php
> +it('can get null when collects is null', function (): void {
poprawiono `can get` na `return`

2024-10-08 08:05 UTC, rooosiu commented on tests/Resource/ApiCollectionTest.php
> +it('can get null when collects is missing', function (): void {
poprawiono `can get` na `return`

2024-10-08 08:06 UTC, rooosiu commented on tests/Resource/ApiCollectionTest.php
> +it('get response with correct data', function (): void {
poprawiono na return

2024-10-08 08:07 UTC, rooosiu commented on tests/Resource/ApiCollectionTest.php
> +it('can get null when resource is empty array & collects is defined', function (): void {
poprawiono `can get` na `return`

2024-10-08 08:10 UTC, rooosiu commented on tests/Resource/AdditionalResourceDataTest.php
> +it('can includes apiVersion in the response', function () {
poprawiono

2024-10-08 08:12 UTC, rudashi requested changes

2024-10-08 08:12 UTC, rudashi commented on tests/Resource/ApiCollectionTest.php
> +
słowo kluczowe `IT` oznacza plik testowany, tutaj jest nim ApiCollection
Czy ApiCollection zwraca NULL?
Nie, zwraca property `collects`
Tym samym test wprowadza w błąd.

test(`collect property returns null when not provided`)

Analogicznie każdy taki test, który robi co innego niż jest opisane.

2024-10-08 08:12 UTC, rudashi commented on tests/Resource/ApiResourceTest.php
> +<?php
Czyli są warunkowe. 
Czy ` it('can get array', function (): void  ` jeżeli w `$this->resource` podam inny typ to dostanę object, bool, int, float?

2024-10-08 08:12 UTC, rudashi commented on tests/Resource/ApiResourceTest.php
> +
Nazwa testu sugeruje możliwość, lub nie, stworzenia Collection.
Sam Test sprawdza czy wykorzystanie metody `collection()` tworzy inny niż customowy obiekt.

2024-10-08 08:12 UTC, rudashi commented on tests/Resource/ApiResourceTest.php
> +        ->sequence(
Na pewno nie tak... a metoda `->and()` ?

2024-10-08 08:12 UTC, rudashi commented on tests/Resource/FixtureModel.php
> +class FixtureModel extends Model
Lepiej, ale czy widzisz zmienną `$attributes`?

`static::unguard();` nie powinna być za parent...

2024-10-08 08:42 UTC, rooosiu commented on README.md
> +- `noContent()` - creates an ApiResource instance with `true` as the resource value, which allows the response to be returned with an HTTP 204 No Content code.
czyli opis ograniczyć do `Allows the response to be returned with an HTTP 204 (No Content) status code.`

2024-10-08 08:53 UTC, rooosiu commented on src/Bundles/Resource/AdditionalResourceData.php
> +{
uznałem, że jeżeli wykorzystywany jest w dwóch klasach to muszę to uwzględnić.

2024-10-08 09:05 UTC, rooosiu commented on tests/Resource/ApiResourceTest.php
> +<?php
albo zwróci array albo walnie errorem, czyli nie zwróci nigdy innego typu. czyli usunąć słowo `can` z nazwy ?

2024-10-08 09:14 UTC, rooosiu commented on tests/Resource/AdditionalResourceDataTest.php
> +
może być  it `return the api version`?

2024-10-08 09:36 UTC, rooosiu commented on tests/Resource/ApiResourceTest.php
> +
tu nie mam pomysłu na nazwę lub zmianę testu

2024-10-08 10:15 UTC, rudashi commented on src/Bundles/Resource/AdditionalResourceData.php
> +{
Ale co ma Trait do tego? 
Postaw się w sytuacje takiego traita. 
Czy wykorzystujesz gdzieś te metody?
Czy masz wiedze, świadomość jak jesteś wykorzystywany?
Skąd w ogóle pewność, że to ApiResource i ApiCollection?

Nie dodawaj na ślepo kodu.

Nie o taki phpdoc chodziło.

2024-10-08 10:17 UTC, rudashi commented on tests/Resource/FixtureModel.php
> +class FixtureModel extends Model
Przypatrz się po co jest argument $attributes i czemu jest przekazywany do parenta.

2024-10-08 15:13 UTC, closed without merging